//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.07.12 at 09:24:55 PM ICT 
//


package com.accenture.dt.dete.domain.schema.common;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;
import com.accenture.dt.dete.domain.schema.digitalasset.Asset;
import com.accenture.dt.dete.domain.schema.digitalasset.AssetComponentAssociation;
import com.accenture.dt.dete.domain.schema.digitalasset.AssetPart;
import com.accenture.dt.dete.domain.schema.digitalasset.AssetPartLocation;
import com.accenture.dt.dete.domain.schema.digitalasset.Collection;
import com.accenture.dt.dete.domain.schema.digitalasset.Component;
import com.accenture.dt.dete.domain.schema.digitalasset.ComponentFile;
import com.accenture.dt.dete.domain.schema.digitalasset.ParentSource;
import com.accenture.dt.dete.domain.schema.digitalasset.Product;
import com.accenture.dt.dete.domain.schema.digitalasset.ProductPart;
import com.accenture.dt.dete.domain.schema.digitalasset.Rendition;
import com.accenture.dt.dete.domain.schema.studioasset.ReceivedAsset;
import com.accenture.dt.dete.domain.schema.studioasset.ReceivedTitle;


/**
 * <p>Java class for baseEntity complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="baseEntity"&gt;
 *   &lt;complexContent&gt;
 *     &lt;extension base="{http://dete.dt.accenture.com/domain/schema/common}baseObject"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="createdDate" type="{http://www.w3.org/2001/XMLSchema}dateTime" minOccurs="0"/&gt;
 *         &lt;element name="modifiedDate" type="{http://www.w3.org/2001/XMLSchema}dateTime" minOccurs="0"/&gt;
 *         &lt;element name="ormId" type="{http://www.w3.org/2001/XMLSchema}long" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/extension&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "baseEntity", propOrder = {
    "createdDate",
    "modifiedDate",
    "ormId"
})
@XmlSeeAlso({
    ComponentFile.class,
    ParentSource.class,
    BaseParameter.class,
    Collection.class,
    Product.class,
    AssetPart.class,
    Rendition.class,
    ReceivedAsset.class,
    ReceivedTitle.class,
    ProductPart.class,
    AssetComponentAssociation.class,
    Asset.class,
    AssetPartLocation.class,
    Component.class
})
public abstract class BaseEntity
    extends BaseObject
{

    @XmlSchemaType(name = "dateTime")
    protected XMLGregorianCalendar createdDate;
    @XmlSchemaType(name = "dateTime")
    protected XMLGregorianCalendar modifiedDate;
    protected Long ormId;

    /**
     * Gets the value of the createdDate property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getCreatedDate() {
        return createdDate;
    }

    /**
     * Sets the value of the createdDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setCreatedDate(XMLGregorianCalendar value) {
        this.createdDate = value;
    }

    /**
     * Gets the value of the modifiedDate property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getModifiedDate() {
        return modifiedDate;
    }

    /**
     * Sets the value of the modifiedDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setModifiedDate(XMLGregorianCalendar value) {
        this.modifiedDate = value;
    }

    /**
     * Gets the value of the ormId property.
     * 
     * @return
     *     possible object is
     *     {@link Long }
     *     
     */
    public Long getOrmId() {
        return ormId;
    }

    /**
     * Sets the value of the ormId property.
     * 
     * @param value
     *     allowed object is
     *     {@link Long }
     *     
     */
    public void setOrmId(Long value) {
        this.ormId = value;
    }

}
