//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.07.12 at 09:24:55 PM ICT 
//


package com.accenture.dt.dete.domain.schema.studioasset;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import com.accenture.dt.dete.domain.schema.digitalasset.CompositeComponent;


/**
 * <p>Java class for audioConfigurationComponent complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="audioConfigurationComponent"&gt;
 *   &lt;complexContent&gt;
 *     &lt;extension base="{http://dete.dt.accenture.com/domain/schema/digitalasset}compositeComponent"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="codecVersion" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="runTime" type="{http://www.w3.org/2001/XMLSchema}long" minOccurs="0"/&gt;
 *         &lt;element name="startTimecode" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="language" type="{http://dete.dt.accenture.com/domain/schema/studioasset}language" minOccurs="0"/&gt;
 *         &lt;element name="content" type="{http://dete.dt.accenture.com/domain/schema/studioasset}audioContent" minOccurs="0"/&gt;
 *         &lt;element name="soundMix" type="{http://dete.dt.accenture.com/domain/schema/studioasset}audioSoundMix" minOccurs="0"/&gt;
 *         &lt;element name="soundField" type="{http://dete.dt.accenture.com/domain/schema/studioasset}audioSoundField" minOccurs="0"/&gt;
 *         &lt;element name="numChannels" type="{http://www.w3.org/2001/XMLSchema}int" minOccurs="0"/&gt;
 *         &lt;element name="trackConfiguration" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="standard" type="{http://dete.dt.accenture.com/domain/schema/studioasset}standard" minOccurs="0"/&gt;
 *         &lt;element name="codec" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="audioFormat" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="sampleRate" type="{http://www.w3.org/2001/XMLSchema}long" minOccurs="0"/&gt;
 *         &lt;element name="bitRate" type="{http://www.w3.org/2001/XMLSchema}long" minOccurs="0"/&gt;
 *         &lt;element name="bitDepth" type="{http://www.w3.org/2001/XMLSchema}int" minOccurs="0"/&gt;
 *         &lt;element name="dropFrame" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/extension&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "audioConfigurationComponent", propOrder = {
    "codecVersion",
    "runTime",
    "startTimecode",
    "language",
    "content",
    "soundMix",
    "soundField",
    "numChannels",
    "trackConfiguration",
    "standard",
    "codec",
    "audioFormat",
    "sampleRate",
    "bitRate",
    "bitDepth",
    "dropFrame"
})
public class AudioConfigurationComponent
    extends CompositeComponent
{

    protected String codecVersion;
    protected Long runTime;
    protected String startTimecode;
    @XmlSchemaType(name = "string")
    protected Language language;
    @XmlSchemaType(name = "string")
    protected AudioContent content;
    protected String soundMix;
    @XmlSchemaType(name = "string")
    protected AudioSoundField soundField;
    protected Integer numChannels;
    protected String trackConfiguration;
    protected String standard;
    protected String codec;
    protected String audioFormat;
    protected Long sampleRate;
    protected Long bitRate;
    protected Integer bitDepth;
    protected Boolean dropFrame;

    /**
     * Gets the value of the codecVersion property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCodecVersion() {
        return codecVersion;
    }

    /**
     * Sets the value of the codecVersion property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCodecVersion(String value) {
        this.codecVersion = value;
    }

    /**
     * Gets the value of the runTime property.
     * 
     * @return
     *     possible object is
     *     {@link Long }
     *     
     */
    public Long getRunTime() {
        return runTime;
    }

    /**
     * Sets the value of the runTime property.
     * 
     * @param value
     *     allowed object is
     *     {@link Long }
     *     
     */
    public void setRunTime(Long value) {
        this.runTime = value;
    }

    /**
     * Gets the value of the startTimecode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getStartTimecode() {
        return startTimecode;
    }

    /**
     * Sets the value of the startTimecode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setStartTimecode(String value) {
        this.startTimecode = value;
    }

    /**
     * Gets the value of the language property.
     * 
     * @return
     *     possible object is
     *     {@link Language }
     *     
     */
    public Language getLanguage() {
        return language;
    }

    /**
     * Sets the value of the language property.
     * 
     * @param value
     *     allowed object is
     *     {@link Language }
     *     
     */
    public void setLanguage(Language value) {
        this.language = value;
    }

    /**
     * Gets the value of the content property.
     * 
     * @return
     *     possible object is
     *     {@link AudioContent }
     *     
     */
    public AudioContent getContent() {
        return content;
    }

    /**
     * Sets the value of the content property.
     * 
     * @param value
     *     allowed object is
     *     {@link AudioContent }
     *     
     */
    public void setContent(AudioContent value) {
        this.content = value;
    }

    /**
     * Gets the value of the soundMix property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSoundMix() {
        return soundMix;
    }

    /**
     * Sets the value of the soundMix property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSoundMix(String value) {
        this.soundMix = value;
    }

    /**
     * Gets the value of the soundField property.
     * 
     * @return
     *     possible object is
     *     {@link AudioSoundField }
     *     
     */
    public AudioSoundField getSoundField() {
        return soundField;
    }

    /**
     * Sets the value of the soundField property.
     * 
     * @param value
     *     allowed object is
     *     {@link AudioSoundField }
     *     
     */
    public void setSoundField(AudioSoundField value) {
        this.soundField = value;
    }

    /**
     * Gets the value of the numChannels property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getNumChannels() {
        return numChannels;
    }

    /**
     * Sets the value of the numChannels property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setNumChannels(Integer value) {
        this.numChannels = value;
    }

    /**
     * Gets the value of the trackConfiguration property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTrackConfiguration() {
        return trackConfiguration;
    }

    /**
     * Sets the value of the trackConfiguration property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTrackConfiguration(String value) {
        this.trackConfiguration = value;
    }

    /**
     * Gets the value of the standard property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getStandard() {
        return standard;
    }

    /**
     * Sets the value of the standard property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setStandard(String value) {
        this.standard = value;
    }

    /**
     * Gets the value of the codec property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCodec() {
        return codec;
    }

    /**
     * Sets the value of the codec property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCodec(String value) {
        this.codec = value;
    }

    /**
     * Gets the value of the audioFormat property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAudioFormat() {
        return audioFormat;
    }

    /**
     * Sets the value of the audioFormat property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAudioFormat(String value) {
        this.audioFormat = value;
    }

    /**
     * Gets the value of the sampleRate property.
     * 
     * @return
     *     possible object is
     *     {@link Long }
     *     
     */
    public Long getSampleRate() {
        return sampleRate;
    }

    /**
     * Sets the value of the sampleRate property.
     * 
     * @param value
     *     allowed object is
     *     {@link Long }
     *     
     */
    public void setSampleRate(Long value) {
        this.sampleRate = value;
    }

    /**
     * Gets the value of the bitRate property.
     * 
     * @return
     *     possible object is
     *     {@link Long }
     *     
     */
    public Long getBitRate() {
        return bitRate;
    }

    /**
     * Sets the value of the bitRate property.
     * 
     * @param value
     *     allowed object is
     *     {@link Long }
     *     
     */
    public void setBitRate(Long value) {
        this.bitRate = value;
    }

    /**
     * Gets the value of the bitDepth property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getBitDepth() {
        return bitDepth;
    }

    /**
     * Sets the value of the bitDepth property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setBitDepth(Integer value) {
        this.bitDepth = value;
    }

    /**
     * Gets the value of the dropFrame property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isDropFrame() {
        return dropFrame;
    }

    /**
     * Sets the value of the dropFrame property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setDropFrame(Boolean value) {
        this.dropFrame = value;
    }

}
