//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.07.12 at 09:24:55 PM ICT 
//


package com.accenture.dt.dete.domain.schema.studioasset;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for audioSoundField.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="audioSoundField"&gt;
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *     &lt;enumeration value="CDS"/&gt;
 *     &lt;enumeration value="DOLBYSR"/&gt;
 *     &lt;enumeration value="DOLBYSRD"/&gt;
 *     &lt;enumeration value="DOLBYSVA"/&gt;
 *     &lt;enumeration value="DTS"/&gt;
 *     &lt;enumeration value="DVD"/&gt;
 *     &lt;enumeration value="HIFI"/&gt;
 *     &lt;enumeration value="NEARFLD"/&gt;
 *     &lt;enumeration value="PERSPECTA"/&gt;
 *     &lt;enumeration value="SDDS"/&gt;
 *     &lt;enumeration value="THEATRICAL_AUDIO"/&gt;
 *     &lt;enumeration value="TV"/&gt;
 *     &lt;enumeration value="AUDIO_LIMITING"/&gt;
 *     &lt;enumeration value="EURO_LIMITING"/&gt;
 *   &lt;/restriction&gt;
 * &lt;/simpleType&gt;
 * </pre>
 * 
 */
@XmlType(name = "audioSoundField")
@XmlEnum
public enum AudioSoundField {

    CDS,
    DOLBYSR,
    DOLBYSRD,
    DOLBYSVA,
    DTS,
    DVD,
    HIFI,
    NEARFLD,
    PERSPECTA,
    SDDS,
    THEATRICAL_AUDIO,
    TV,
    AUDIO_LIMITING,
    EURO_LIMITING;

    public String value() {
        return name();
    }

    public static AudioSoundField fromValue(String v) {
        return valueOf(v);
    }

}
