//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.07.12 at 09:24:55 PM ICT 
//


package com.accenture.dt.dete.domain.schema.studioasset;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for audioContent.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="audioContent"&gt;
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *     &lt;enumeration value="ADR"/&gt;
 *     &lt;enumeration value="AUDIENCE"/&gt;
 *     &lt;enumeration value="BACKGROUND"/&gt;
 *     &lt;enumeration value="BLANK"/&gt;
 *     &lt;enumeration value="CLICK_TRACK"/&gt;
 *     &lt;enumeration value="COMMENTARY"/&gt;
 *     &lt;enumeration value="COMPOSITE"/&gt;
 *     &lt;enumeration value="COMPOSITE_ALTERNATE"/&gt;
 *     &lt;enumeration value="COMPOSITE_LIMITED"/&gt;
 *     &lt;enumeration value="COMP_WO_LAFFS"/&gt;
 *     &lt;enumeration value="COMP_W_LAFFS"/&gt;
 *     &lt;enumeration value="CUE"/&gt;
 *     &lt;enumeration value="DESC_AUDIO"/&gt;
 *     &lt;enumeration value="DESC_AUDIO_AMERICAN"/&gt;
 *     &lt;enumeration value="DESC_AUDIO_BRITISH"/&gt;
 *     &lt;enumeration value="DIALOGUE_EFFECTS"/&gt;
 *     &lt;enumeration value="DIALOGUE_GUIDE"/&gt;
 *     &lt;enumeration value="DIALOGUE_MUSIC"/&gt;
 *     &lt;enumeration value="DIALOGUE_PRE_DUB"/&gt;
 *     &lt;enumeration value="DIALOGUE_STEM"/&gt;
 *     &lt;enumeration value="DIALOGUE_STEM_MIN_LAFFS"/&gt;
 *     &lt;enumeration value="EFFECTS_PREDUB"/&gt;
 *     &lt;enumeration value="EFFECTS_STEM"/&gt;
 *     &lt;enumeration value="FILLED_EFFECTS"/&gt;
 *     &lt;enumeration value="FOLEY"/&gt;
 *     &lt;enumeration value="LAUGHS"/&gt;
 *     &lt;enumeration value="LECTORING"/&gt;
 *     &lt;enumeration value="LOW_FREQ_EFECT"/&gt;
 *     &lt;enumeration value="MFX_FILLED"/&gt;
 *     &lt;enumeration value="MFX_MONO"/&gt;
 *     &lt;enumeration value="MFX_STEM"/&gt;
 *     &lt;enumeration value="MFX_STEREO"/&gt;
 *     &lt;enumeration value="MFX_WO_ANNC"/&gt;
 *     &lt;enumeration value="MUSIC_PRE_DUB"/&gt;
 *     &lt;enumeration value="MUSIC_SCORE"/&gt;
 *     &lt;enumeration value="MUSIC_STEM"/&gt;
 *     &lt;enumeration value="NARRATION"/&gt;
 *     &lt;enumeration value="OPTIONAL"/&gt;
 *     &lt;enumeration value="OTHER"/&gt;
 *     &lt;enumeration value="PRINTMASTER"/&gt;
 *     &lt;enumeration value="PRODUCTION_AUDIO"/&gt;
 *     &lt;enumeration value="SYNCH_REFERENCE"/&gt;
 *     &lt;enumeration value="VERIFY"/&gt;
 *     &lt;enumeration value="VERIFY_DIALOGUE"/&gt;
 *     &lt;enumeration value="VOCALS"/&gt;
 *     &lt;enumeration value="VOICE_OVER"/&gt;
 *   &lt;/restriction&gt;
 * &lt;/simpleType&gt;
 * </pre>
 * 
 */
@XmlType(name = "audioContent")
@XmlEnum
public enum AudioContent {

    ADR,
    AUDIENCE,
    BACKGROUND,
    BLANK,
    CLICK_TRACK,
    COMMENTARY,
    COMPOSITE,
    COMPOSITE_ALTERNATE,
    COMPOSITE_LIMITED,
    COMP_WO_LAFFS,
    COMP_W_LAFFS,
    CUE,
    DESC_AUDIO,
    DESC_AUDIO_AMERICAN,
    DESC_AUDIO_BRITISH,
    DIALOGUE_EFFECTS,
    DIALOGUE_GUIDE,
    DIALOGUE_MUSIC,
    DIALOGUE_PRE_DUB,
    DIALOGUE_STEM,
    DIALOGUE_STEM_MIN_LAFFS,
    EFFECTS_PREDUB,
    EFFECTS_STEM,
    FILLED_EFFECTS,
    FOLEY,
    LAUGHS,
    LECTORING,
    LOW_FREQ_EFECT,
    MFX_FILLED,
    MFX_MONO,
    MFX_STEM,
    MFX_STEREO,
    MFX_WO_ANNC,
    MUSIC_PRE_DUB,
    MUSIC_SCORE,
    MUSIC_STEM,
    NARRATION,
    OPTIONAL,
    OTHER,
    PRINTMASTER,
    PRODUCTION_AUDIO,
    SYNCH_REFERENCE,
    VERIFY,
    VERIFY_DIALOGUE,
    VOCALS,
    VOICE_OVER;

    public String value() {
        return name();
    }

    public static AudioContent fromValue(String v) {
        return valueOf(v);
    }

}
