//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.07.12 at 09:24:55 PM ICT 
//


package com.accenture.dt.dete.domain.schema.studioasset;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for channelPosition.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="channelPosition"&gt;
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *     &lt;enumeration value="MONO"/&gt;
 *     &lt;enumeration value="LEFT"/&gt;
 *     &lt;enumeration value="RIGHT"/&gt;
 *     &lt;enumeration value="LEFT_TOTAL"/&gt;
 *     &lt;enumeration value="RIGHT_TOTAL"/&gt;
 *     &lt;enumeration value="CENTER"/&gt;
 *     &lt;enumeration value="LEFT_SURROUND"/&gt;
 *     &lt;enumeration value="RIGHT_SURROUND"/&gt;
 *     &lt;enumeration value="DOLBY_E_STREAM"/&gt;
 *     &lt;enumeration value="SUB_WOOFER"/&gt;
 *     &lt;enumeration value="CENTER_SURROUND"/&gt;
 *     &lt;enumeration value="VERIFY_SURROUND"/&gt;
 *     &lt;enumeration value="VERIFY"/&gt;
 *     &lt;enumeration value="BOOM"/&gt;
 *     &lt;enumeration value="CENTER_EXTRA"/&gt;
 *     &lt;enumeration value="LEFT_BOOM"/&gt;
 *     &lt;enumeration value="LEFT_CENTER"/&gt;
 *     &lt;enumeration value="RIGHT_BOOM"/&gt;
 *     &lt;enumeration value="RIGHT_CENTER"/&gt;
 *     &lt;enumeration value="MONO_L_R"/&gt;
 *     &lt;enumeration value="MONO_SURROUND"/&gt;
 *     &lt;enumeration value="PCM"/&gt;
 *     &lt;enumeration value="LINEAR"/&gt;
 *     &lt;enumeration value="HIFI"/&gt;
 *     &lt;enumeration value="LOW_FREQ_EFECT"/&gt;
 *   &lt;/restriction&gt;
 * &lt;/simpleType&gt;
 * </pre>
 * 
 */
@XmlType(name = "channelPosition")
@XmlEnum
public enum ChannelPosition {

    MONO,
    LEFT,
    RIGHT,
    LEFT_TOTAL,
    RIGHT_TOTAL,
    CENTER,
    LEFT_SURROUND,
    RIGHT_SURROUND,
    DOLBY_E_STREAM,
    SUB_WOOFER,
    CENTER_SURROUND,
    VERIFY_SURROUND,
    VERIFY,
    BOOM,
    CENTER_EXTRA,
    LEFT_BOOM,
    LEFT_CENTER,
    RIGHT_BOOM,
    RIGHT_CENTER,
    MONO_L_R,
    MONO_SURROUND,
    PCM,
    LINEAR,
    HIFI,
    LOW_FREQ_EFECT;

    public String value() {
        return name();
    }

    public static ChannelPosition fromValue(String v) {
        return valueOf(v);
    }

}
