//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.07.12 at 09:24:55 PM ICT 
//


package com.accenture.dt.dete.domain.schema.studioasset;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for language.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="language"&gt;
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *     &lt;enumeration value="AFRIKAANS"/&gt;
 *     &lt;enumeration value="ALBANIAN"/&gt;
 *     &lt;enumeration value="ARABIC"/&gt;
 *     &lt;enumeration value="ARABIC_CLASSIC"/&gt;
 *     &lt;enumeration value="ARABIC_EGPYTIAN"/&gt;
 *     &lt;enumeration value="ARMENIAN"/&gt;
 *     &lt;enumeration value="BASQUE"/&gt;
 *     &lt;enumeration value="BAHASA_INDONESIAN"/&gt;
 *     &lt;enumeration value="BAHASA_MALAY"/&gt;
 *     &lt;enumeration value="BOSNIAN"/&gt;
 *     &lt;enumeration value="BULGARIAN"/&gt;
 *     &lt;enumeration value="CHINESE_CANTONESE"/&gt;
 *     &lt;enumeration value="CHINESE_MANDARIN_MNLAND"/&gt;
 *     &lt;enumeration value="CHINESE_MANDARIN_TAIWAN"/&gt;
 *     &lt;enumeration value="CHINESE_VERIFY_DIALECT"/&gt;
 *     &lt;enumeration value="CROATIAN"/&gt;
 *     &lt;enumeration value="CZECH"/&gt;
 *     &lt;enumeration value="DANISH"/&gt;
 *     &lt;enumeration value="DUTCH"/&gt;
 *     &lt;enumeration value="ENGLISH"/&gt;
 *     &lt;enumeration value="ESTONIAN"/&gt;
 *     &lt;enumeration value="FARSI_IRANIAN"/&gt;
 *     &lt;enumeration value="FINNISH"/&gt;
 *     &lt;enumeration value="FLEMISH_DUTCH"/&gt;
 *     &lt;enumeration value="FLEMISH_FRENCH"/&gt;
 *     &lt;enumeration value="FLEMISH"/&gt;
 *     &lt;enumeration value="FRENCH_CANADIAN"/&gt;
 *     &lt;enumeration value="FRENCH_PARISIAN"/&gt;
 *     &lt;enumeration value="FRENCH_VERIFY_DIALECT"/&gt;
 *     &lt;enumeration value="GAELIC_IRELAND"/&gt;
 *     &lt;enumeration value="GERMAN"/&gt;
 *     &lt;enumeration value="GEORGIAN"/&gt;
 *     &lt;enumeration value="GREEK"/&gt;
 *     &lt;enumeration value="HEBREW"/&gt;
 *     &lt;enumeration value="HINDI"/&gt;
 *     &lt;enumeration value="HMONG"/&gt;
 *     &lt;enumeration value="HUNGARIAN"/&gt;
 *     &lt;enumeration value="ICELANDIC"/&gt;
 *     &lt;enumeration value="ITALIAN"/&gt;
 *     &lt;enumeration value="JAPANESE"/&gt;
 *     &lt;enumeration value="KOREAN"/&gt;
 *     &lt;enumeration value="LATVIAN"/&gt;
 *     &lt;enumeration value="ARABIC_LEBANESE"/&gt;
 *     &lt;enumeration value="LITHUANIAN"/&gt;
 *     &lt;enumeration value="MACEDONIAN"/&gt;
 *     &lt;enumeration value="MALAY"/&gt;
 *     &lt;enumeration value="MALAYALAM"/&gt;
 *     &lt;enumeration value="MONGOLIAN"/&gt;
 *     &lt;enumeration value="NORWEGIAN"/&gt;
 *     &lt;enumeration value="POLISH"/&gt;
 *     &lt;enumeration value="PORTUGUESE_BRAZIL"/&gt;
 *     &lt;enumeration value="PORTUGUESE_PORTUGAL"/&gt;
 *     &lt;enumeration value="PORTUGUESE_VERIFY"/&gt;
 *     &lt;enumeration value="ROMANIAN"/&gt;
 *     &lt;enumeration value="RUSSIAN"/&gt;
 *     &lt;enumeration value="SERBIAN"/&gt;
 *     &lt;enumeration value="SLOVAK"/&gt;
 *     &lt;enumeration value="SLOVENIAN"/&gt;
 *     &lt;enumeration value="SPANISH_ARGENTINEAN"/&gt;
 *     &lt;enumeration value="SPANISH_CASTILLIAN"/&gt;
 *     &lt;enumeration value="SPANISH_CATALAN"/&gt;
 *     &lt;enumeration value="SPANISH_CHILEAN"/&gt;
 *     &lt;enumeration value="SPANISH_COLOMBIAN"/&gt;
 *     &lt;enumeration value="SPANISH_LATIN"/&gt;
 *     &lt;enumeration value="SPANISH_NEUTRAL"/&gt;
 *     &lt;enumeration value="SPANISH_MEXICAN"/&gt;
 *     &lt;enumeration value="SPANISH_PERUVIAN"/&gt;
 *     &lt;enumeration value="SPANISH_VERIFY_DIALECT"/&gt;
 *     &lt;enumeration value="SWEDISH"/&gt;
 *     &lt;enumeration value="TAGALOG"/&gt;
 *     &lt;enumeration value="TAMIL_INDIA"/&gt;
 *     &lt;enumeration value="TELUGU_INDIA"/&gt;
 *     &lt;enumeration value="THAI"/&gt;
 *     &lt;enumeration value="TURKISH"/&gt;
 *     &lt;enumeration value="UKRANIAN"/&gt;
 *     &lt;enumeration value="URDU_PAKISTAN"/&gt;
 *     &lt;enumeration value="VIETNAMESE"/&gt;
 *     &lt;enumeration value="WELSH"/&gt;
 *     &lt;enumeration value="YU_SERBIAN"/&gt;
 *   &lt;/restriction&gt;
 * &lt;/simpleType&gt;
 * </pre>
 * 
 */
@XmlType(name = "language")
@XmlEnum
public enum Language {

    AFRIKAANS,
    ALBANIAN,
    ARABIC,
    ARABIC_CLASSIC,
    ARABIC_EGPYTIAN,
    ARMENIAN,
    BASQUE,
    BAHASA_INDONESIAN,
    BAHASA_MALAY,
    BOSNIAN,
    BULGARIAN,
    CHINESE_CANTONESE,
    CHINESE_MANDARIN_MNLAND,
    CHINESE_MANDARIN_TAIWAN,
    CHINESE_VERIFY_DIALECT,
    CROATIAN,
    CZECH,
    DANISH,
    DUTCH,
    ENGLISH,
    ESTONIAN,
    FARSI_IRANIAN,
    FINNISH,
    FLEMISH_DUTCH,
    FLEMISH_FRENCH,
    FLEMISH,
    FRENCH_CANADIAN,
    FRENCH_PARISIAN,
    FRENCH_VERIFY_DIALECT,
    GAELIC_IRELAND,
    GERMAN,
    GEORGIAN,
    GREEK,
    HEBREW,
    HINDI,
    HMONG,
    HUNGARIAN,
    ICELANDIC,
    ITALIAN,
    JAPANESE,
    KOREAN,
    LATVIAN,
    ARABIC_LEBANESE,
    LITHUANIAN,
    MACEDONIAN,
    MALAY,
    MALAYALAM,
    MONGOLIAN,
    NORWEGIAN,
    POLISH,
    PORTUGUESE_BRAZIL,
    PORTUGUESE_PORTUGAL,
    PORTUGUESE_VERIFY,
    ROMANIAN,
    RUSSIAN,
    SERBIAN,
    SLOVAK,
    SLOVENIAN,
    SPANISH_ARGENTINEAN,
    SPANISH_CASTILLIAN,
    SPANISH_CATALAN,
    SPANISH_CHILEAN,
    SPANISH_COLOMBIAN,
    SPANISH_LATIN,
    SPANISH_NEUTRAL,
    SPANISH_MEXICAN,
    SPANISH_PERUVIAN,
    SPANISH_VERIFY_DIALECT,
    SWEDISH,
    TAGALOG,
    TAMIL_INDIA,
    TELUGU_INDIA,
    THAI,
    TURKISH,
    UKRANIAN,
    URDU_PAKISTAN,
    VIETNAMESE,
    WELSH,
    YU_SERBIAN;

    public String value() {
        return name();
    }

    public static Language fromValue(String v) {
        return valueOf(v);
    }

}
