//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.07.12 at 09:24:55 PM ICT 
//


package com.accenture.dt.dete.domain.schema.studioasset;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.accenture.dt.dete.domain.schema.studioasset package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _Series_QNAME = new QName("http://dete.dt.accenture.com/domain/schema/studioasset", "series");
    private final static QName _Title_QNAME = new QName("http://dete.dt.accenture.com/domain/schema/studioasset", "title");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.accenture.dt.dete.domain.schema.studioasset
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link Series }
     * 
     */
    public Series createSeries() {
        return new Series();
    }

    /**
     * Create an instance of {@link Title }
     * 
     */
    public Title createTitle() {
        return new Title();
    }

    /**
     * Create an instance of {@link AudioChannelComponent }
     * 
     */
    public AudioChannelComponent createAudioChannelComponent() {
        return new AudioChannelComponent();
    }

    /**
     * Create an instance of {@link AudioConfigurationComponent }
     * 
     */
    public AudioConfigurationComponent createAudioConfigurationComponent() {
        return new AudioConfigurationComponent();
    }

    /**
     * Create an instance of {@link ClosedCaptionComponent }
     * 
     */
    public ClosedCaptionComponent createClosedCaptionComponent() {
        return new ClosedCaptionComponent();
    }

    /**
     * Create an instance of {@link ConformanceAssociation }
     * 
     */
    public ConformanceAssociation createConformanceAssociation() {
        return new ConformanceAssociation();
    }

    /**
     * Create an instance of {@link ConformanceGroup }
     * 
     */
    public ConformanceGroup createConformanceGroup() {
        return new ConformanceGroup();
    }

    /**
     * Create an instance of {@link PlaylistSegment }
     * 
     */
    public PlaylistSegment createPlaylistSegment() {
        return new PlaylistSegment();
    }

    /**
     * Create an instance of {@link EditedVersion }
     * 
     */
    public EditedVersion createEditedVersion() {
        return new EditedVersion();
    }

    /**
     * Create an instance of {@link ReceivedAsset }
     * 
     */
    public ReceivedAsset createReceivedAsset() {
        return new ReceivedAsset();
    }

    /**
     * Create an instance of {@link ReceivedTitle }
     * 
     */
    public ReceivedTitle createReceivedTitle() {
        return new ReceivedTitle();
    }

    /**
     * Create an instance of {@link TitleSegment }
     * 
     */
    public TitleSegment createTitleSegment() {
        return new TitleSegment();
    }

    /**
     * Create an instance of {@link StandaloneAssociation }
     * 
     */
    public StandaloneAssociation createStandaloneAssociation() {
        return new StandaloneAssociation();
    }

    /**
     * Create an instance of {@link StandaloneGroup }
     * 
     */
    public StandaloneGroup createStandaloneGroup() {
        return new StandaloneGroup();
    }

    /**
     * Create an instance of {@link SubtitleComponent }
     * 
     */
    public SubtitleComponent createSubtitleComponent() {
        return new SubtitleComponent();
    }

    /**
     * Create an instance of {@link TitleAssetPartLocation }
     * 
     */
    public TitleAssetPartLocation createTitleAssetPartLocation() {
        return new TitleAssetPartLocation();
    }

    /**
     * Create an instance of {@link VideoComponent }
     * 
     */
    public VideoComponent createVideoComponent() {
        return new VideoComponent();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Series }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://dete.dt.accenture.com/domain/schema/studioasset", name = "series")
    public JAXBElement<Series> createSeries(Series value) {
        return new JAXBElement<Series>(_Series_QNAME, Series.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Title }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://dete.dt.accenture.com/domain/schema/studioasset", name = "title")
    public JAXBElement<Title> createTitle(Title value) {
        return new JAXBElement<Title>(_Title_QNAME, Title.class, null, value);
    }

}
