//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.07.12 at 09:24:55 PM ICT 
//


package com.accenture.dt.dete.domain.schema.studioasset;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for playlistSegmentType.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="playlistSegmentType"&gt;
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *     &lt;enumeration value="BLACK"/&gt;
 *     &lt;enumeration value="PROGRAM"/&gt;
 *     &lt;enumeration value="SMPTE_BARS"/&gt;
 *     &lt;enumeration value="SLATE"/&gt;
 *     &lt;enumeration value="LOGO_PROD_COMPANY"/&gt;
 *     &lt;enumeration value="LOGO_WB_THEATRICAL"/&gt;
 *     &lt;enumeration value="LOGO_WBTV_DISTRIBUTION"/&gt;
 *     &lt;enumeration value="LOGO_WHV_DISTRIBUTION"/&gt;
 *     &lt;enumeration value="CARD_MPAA"/&gt;
 *     &lt;enumeration value="CARD_FBI"/&gt;
 *     &lt;enumeration value="CARD_INTERPOL"/&gt;
 *     &lt;enumeration value="END_CREDITS"/&gt;
 *     &lt;enumeration value="TEXTLESS_TAIL"/&gt;
 *     &lt;enumeration value="ENTR_ACTE"/&gt;
 *     &lt;enumeration value="RECAP"/&gt;
 *     &lt;enumeration value="PREVIEW"/&gt;
 *     &lt;enumeration value="OVERTURE"/&gt;
 *     &lt;enumeration value="DISCLAIMER"/&gt;
 *     &lt;enumeration value="LOGO_DEFAULT_DISTRIBUTION"/&gt;
 *     &lt;enumeration value="LOGO_WBTV_DISTRIBUTION_ANNIVERSARY"/&gt;
 *     &lt;enumeration value="LOGO_WHV_DISTRIBUTION_ANNIVERSARY"/&gt;
 *     &lt;enumeration value="LOGO_WB_THEATRICAL_ANNIVERSARY"/&gt;
 *     &lt;enumeration value="LOGO_WB_PAYTV"/&gt;
 *     &lt;enumeration value="BUMPER"/&gt;
 *     &lt;enumeration value="TRAILER"/&gt;
 *     &lt;enumeration value="PROMO"/&gt;
 *     &lt;enumeration value="COMMERCIAL_BLACK"/&gt;
 *     &lt;enumeration value="LOGO_WB_THEATRICAL_ANNIVERSARY_PROD_AUDIO"/&gt;
 *     &lt;enumeration value="LOGO_WHV_DISTRIBUTION_ANNIVERSARY_PROD_AUDIO"/&gt;
 *     &lt;enumeration value="LOGO_WBTV_DISTRIBUTION_ANNIVERSARY_PROD_AUDIO"/&gt;
 *     &lt;enumeration value="EXIT_MUSIC"/&gt;
 *     &lt;enumeration value="PREVIEW_PROD_AUDIO"/&gt;
 *     &lt;enumeration value="CALL_TO_ACTION"/&gt;
 *     &lt;enumeration value="RECAP_PROD_AUDIO"/&gt;
 *     &lt;enumeration value="COUNTDOWN"/&gt;
 *     &lt;enumeration value="TRAILER_PROD_AUDIO"/&gt;
 *     &lt;enumeration value="LOGO_WB_THEATRICAL_PROD_AUDIO"/&gt;
 *     &lt;enumeration value="LOGO_WHV_DISTRIBUTION_PROD_AUDIO"/&gt;
 *     &lt;enumeration value="LOGO_WBTV_DISTRIBUTION_PROD_AUDIO"/&gt;
 *     &lt;enumeration value="CARD_COPYRIGHT_CANADIAN_ENGLISH"/&gt;
 *     &lt;enumeration value="LOGO_WB_INTERNATIONAL"/&gt;
 *     &lt;enumeration value="LOGO_WB_UK"/&gt;
 *     &lt;enumeration value="CARD_COPYRIGHT_WBTV"/&gt;
 *     &lt;enumeration value="CARD_LEGAL_WARNING_DANISH"/&gt;
 *     &lt;enumeration value="CARD_LEGAL_WARNING_FINNISH"/&gt;
 *     &lt;enumeration value="CARD_LEGAL_WARNING_NORWEGIAN"/&gt;
 *     &lt;enumeration value="CARD_LEGAL_WARNING_SWEDISH"/&gt;
 *     &lt;enumeration value="LOGO_WB_WFC"/&gt;
 *     &lt;enumeration value="CALL_TO_ACTION_NON_REMOVABLE"/&gt;
 *     &lt;enumeration value="CARD_COPYRIGHT_RUSSIAN"/&gt;
 *     &lt;enumeration value="CARD_COPYRIGHT_WB_NONTHEATRICAL"/&gt;
 *     &lt;enumeration value="VISA_CARD"/&gt;
 *     &lt;enumeration value="DUBBING_CARD"/&gt;
 *     &lt;enumeration value="PROLOGUE"/&gt;
 *     &lt;enumeration value="CARD_COPYRIGHT_WB_BBC"/&gt;
 *     &lt;enumeration value="CARD_LEGAL_WARNING_DUTCH"/&gt;
 *     &lt;enumeration value="CARD_LEGAL_WARNING_UK_ENGLISH"/&gt;
 *     &lt;enumeration value="CARD_LEGAL_WARNING_SWISS"/&gt;
 *     &lt;enumeration value="POP"/&gt;
 *     &lt;enumeration value="PRODUCT_PLACEMENT"/&gt;
 *     &lt;enumeration value="CARD_COPYRIGHT_GERMAN"/&gt;
 *     &lt;enumeration value="LOGO_NETFLIX_INTRO"/&gt;
 *   &lt;/restriction&gt;
 * &lt;/simpleType&gt;
 * </pre>
 * 
 */
@XmlType(name = "playlistSegmentType")
@XmlEnum
public enum PlaylistSegmentType {

    BLACK,
    PROGRAM,
    SMPTE_BARS,
    SLATE,
    LOGO_PROD_COMPANY,
    LOGO_WB_THEATRICAL,
    LOGO_WBTV_DISTRIBUTION,
    LOGO_WHV_DISTRIBUTION,
    CARD_MPAA,
    CARD_FBI,
    CARD_INTERPOL,
    END_CREDITS,
    TEXTLESS_TAIL,
    ENTR_ACTE,
    RECAP,
    PREVIEW,
    OVERTURE,
    DISCLAIMER,
    LOGO_DEFAULT_DISTRIBUTION,
    LOGO_WBTV_DISTRIBUTION_ANNIVERSARY,
    LOGO_WHV_DISTRIBUTION_ANNIVERSARY,
    LOGO_WB_THEATRICAL_ANNIVERSARY,
    LOGO_WB_PAYTV,
    BUMPER,
    TRAILER,
    PROMO,
    COMMERCIAL_BLACK,
    LOGO_WB_THEATRICAL_ANNIVERSARY_PROD_AUDIO,
    LOGO_WHV_DISTRIBUTION_ANNIVERSARY_PROD_AUDIO,
    LOGO_WBTV_DISTRIBUTION_ANNIVERSARY_PROD_AUDIO,
    EXIT_MUSIC,
    PREVIEW_PROD_AUDIO,
    CALL_TO_ACTION,
    RECAP_PROD_AUDIO,
    COUNTDOWN,
    TRAILER_PROD_AUDIO,
    LOGO_WB_THEATRICAL_PROD_AUDIO,
    LOGO_WHV_DISTRIBUTION_PROD_AUDIO,
    LOGO_WBTV_DISTRIBUTION_PROD_AUDIO,
    CARD_COPYRIGHT_CANADIAN_ENGLISH,
    LOGO_WB_INTERNATIONAL,
    LOGO_WB_UK,
    CARD_COPYRIGHT_WBTV,
    CARD_LEGAL_WARNING_DANISH,
    CARD_LEGAL_WARNING_FINNISH,
    CARD_LEGAL_WARNING_NORWEGIAN,
    CARD_LEGAL_WARNING_SWEDISH,
    LOGO_WB_WFC,
    CALL_TO_ACTION_NON_REMOVABLE,
    CARD_COPYRIGHT_RUSSIAN,
    CARD_COPYRIGHT_WB_NONTHEATRICAL,
    VISA_CARD,
    DUBBING_CARD,
    PROLOGUE,
    CARD_COPYRIGHT_WB_BBC,
    CARD_LEGAL_WARNING_DUTCH,
    CARD_LEGAL_WARNING_UK_ENGLISH,
    CARD_LEGAL_WARNING_SWISS,
    POP,
    PRODUCT_PLACEMENT,
    CARD_COPYRIGHT_GERMAN,
    LOGO_NETFLIX_INTRO;

    public String value() {
        return name();
    }

    public static PlaylistSegmentType fromValue(String v) {
        return valueOf(v);
    }

}
