//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.07.12 at 09:24:55 PM ICT 
//


package com.accenture.dt.dete.domain.schema.studioasset;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;
import com.accenture.dt.dete.domain.schema.digitalasset.Product;


/**
 * <p>Java class for title complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="title"&gt;
 *   &lt;complexContent&gt;
 *     &lt;extension base="{http://dete.dt.accenture.com/domain/schema/digitalasset}product"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="centerCut" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/&gt;
 *         &lt;element name="editedVersion" type="{http://dete.dt.accenture.com/domain/schema/studioasset}editedVersion" maxOccurs="unbounded" minOccurs="0"/&gt;
 *         &lt;element name="episodeNumber" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="episodeSequenceNumber" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="mpmNumber" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="productionNumber" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="releaseDate" type="{http://www.w3.org/2001/XMLSchema}dateTime" minOccurs="0"/&gt;
 *         &lt;element name="releaseNumber" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="securityName" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="securityNameSunsetDate" type="{http://www.w3.org/2001/XMLSchema}dateTime" minOccurs="0"/&gt;
 *         &lt;element name="tenant" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="titleSegment" type="{http://dete.dt.accenture.com/domain/schema/studioasset}titleSegment" maxOccurs="unbounded" minOccurs="0"/&gt;
 *         &lt;element name="type" type="{http://dete.dt.accenture.com/domain/schema/studioasset}titleType" minOccurs="0"/&gt;
 *         &lt;element name="watermarkSunsetDate" type="{http://www.w3.org/2001/XMLSchema}dateTime" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/extension&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "title", propOrder = {
    "centerCut",
    "editedVersion",
    "episodeNumber",
    "episodeSequenceNumber",
    "mpmNumber",
    "productionNumber",
    "releaseDate",
    "releaseNumber",
    "securityName",
    "securityNameSunsetDate",
    "tenant",
    "titleSegment",
    "type",
    "watermarkSunsetDate"
})
public class Title
    extends Product
{

    protected Boolean centerCut;
    protected List<EditedVersion> editedVersion;
    protected String episodeNumber;
    protected String episodeSequenceNumber;
    protected String mpmNumber;
    protected String productionNumber;
    @XmlSchemaType(name = "dateTime")
    protected XMLGregorianCalendar releaseDate;
    protected String releaseNumber;
    protected String securityName;
    @XmlSchemaType(name = "dateTime")
    protected XMLGregorianCalendar securityNameSunsetDate;
    protected String tenant;
    protected List<TitleSegment> titleSegment;
    @XmlSchemaType(name = "string")
    protected TitleType type;
    @XmlSchemaType(name = "dateTime")
    protected XMLGregorianCalendar watermarkSunsetDate;

    /**
     * Gets the value of the centerCut property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isCenterCut() {
        return centerCut;
    }

    /**
     * Sets the value of the centerCut property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setCenterCut(Boolean value) {
        this.centerCut = value;
    }

    /**
     * Gets the value of the editedVersion property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the editedVersion property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getEditedVersion().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link EditedVersion }
     * 
     * 
     */
    public List<EditedVersion> getEditedVersion() {
        if (editedVersion == null) {
            editedVersion = new ArrayList<EditedVersion>();
        }
        return this.editedVersion;
    }

    /**
     * Gets the value of the episodeNumber property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getEpisodeNumber() {
        return episodeNumber;
    }

    /**
     * Sets the value of the episodeNumber property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setEpisodeNumber(String value) {
        this.episodeNumber = value;
    }

    /**
     * Gets the value of the episodeSequenceNumber property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getEpisodeSequenceNumber() {
        return episodeSequenceNumber;
    }

    /**
     * Sets the value of the episodeSequenceNumber property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setEpisodeSequenceNumber(String value) {
        this.episodeSequenceNumber = value;
    }

    /**
     * Gets the value of the mpmNumber property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMpmNumber() {
        return mpmNumber;
    }

    /**
     * Sets the value of the mpmNumber property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMpmNumber(String value) {
        this.mpmNumber = value;
    }

    /**
     * Gets the value of the productionNumber property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getProductionNumber() {
        return productionNumber;
    }

    /**
     * Sets the value of the productionNumber property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setProductionNumber(String value) {
        this.productionNumber = value;
    }

    /**
     * Gets the value of the releaseDate property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getReleaseDate() {
        return releaseDate;
    }

    /**
     * Sets the value of the releaseDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setReleaseDate(XMLGregorianCalendar value) {
        this.releaseDate = value;
    }

    /**
     * Gets the value of the releaseNumber property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getReleaseNumber() {
        return releaseNumber;
    }

    /**
     * Sets the value of the releaseNumber property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setReleaseNumber(String value) {
        this.releaseNumber = value;
    }

    /**
     * Gets the value of the securityName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSecurityName() {
        return securityName;
    }

    /**
     * Sets the value of the securityName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSecurityName(String value) {
        this.securityName = value;
    }

    /**
     * Gets the value of the securityNameSunsetDate property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getSecurityNameSunsetDate() {
        return securityNameSunsetDate;
    }

    /**
     * Sets the value of the securityNameSunsetDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setSecurityNameSunsetDate(XMLGregorianCalendar value) {
        this.securityNameSunsetDate = value;
    }

    /**
     * Gets the value of the tenant property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTenant() {
        return tenant;
    }

    /**
     * Sets the value of the tenant property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTenant(String value) {
        this.tenant = value;
    }

    /**
     * Gets the value of the titleSegment property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the titleSegment property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getTitleSegment().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link TitleSegment }
     * 
     * 
     */
    public List<TitleSegment> getTitleSegment() {
        if (titleSegment == null) {
            titleSegment = new ArrayList<TitleSegment>();
        }
        return this.titleSegment;
    }

    /**
     * Gets the value of the type property.
     * 
     * @return
     *     possible object is
     *     {@link TitleType }
     *     
     */
    public TitleType getType() {
        return type;
    }

    /**
     * Sets the value of the type property.
     * 
     * @param value
     *     allowed object is
     *     {@link TitleType }
     *     
     */
    public void setType(TitleType value) {
        this.type = value;
    }

    /**
     * Gets the value of the watermarkSunsetDate property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getWatermarkSunsetDate() {
        return watermarkSunsetDate;
    }

    /**
     * Sets the value of the watermarkSunsetDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setWatermarkSunsetDate(XMLGregorianCalendar value) {
        this.watermarkSunsetDate = value;
    }

}
