//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.07.12 at 09:24:55 PM ICT 
//


package com.accenture.dt.dete.domain.schema.studioasset;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import com.accenture.dt.dete.domain.schema.digitalasset.Component;


/**
 * <p>Java class for videoComponent complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="videoComponent"&gt;
 *   &lt;complexContent&gt;
 *     &lt;extension base="{http://dete.dt.accenture.com/domain/schema/digitalasset}component"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="frameAspectRatio" type="{http://dete.dt.accenture.com/domain/schema/studioasset}frameAspectRatio" minOccurs="0"/&gt;
 *         &lt;element name="activePictureAspectRatio" type="{http://dete.dt.accenture.com/domain/schema/studioasset}activePictureAspectRatio" minOccurs="0"/&gt;
 *         &lt;element name="cropTopLeftX" type="{http://www.w3.org/2001/XMLSchema}int" minOccurs="0"/&gt;
 *         &lt;element name="cropTopLeftY" type="{http://www.w3.org/2001/XMLSchema}int" minOccurs="0"/&gt;
 *         &lt;element name="cropBottomRightX" type="{http://www.w3.org/2001/XMLSchema}int" minOccurs="0"/&gt;
 *         &lt;element name="cropBottomRightY" type="{http://www.w3.org/2001/XMLSchema}int" minOccurs="0"/&gt;
 *         &lt;element name="runTime" type="{http://www.w3.org/2001/XMLSchema}long" minOccurs="0"/&gt;
 *         &lt;element name="standard" type="{http://dete.dt.accenture.com/domain/schema/studioasset}standard" minOccurs="0"/&gt;
 *         &lt;element name="vbiLinesTop" type="{http://www.w3.org/2001/XMLSchema}int" minOccurs="0"/&gt;
 *         &lt;element name="vbiLinesBottom" type="{http://www.w3.org/2001/XMLSchema}int" minOccurs="0"/&gt;
 *         &lt;element name="fullFrameProcess" type="{http://dete.dt.accenture.com/domain/schema/studioasset}fullFrameProcess" minOccurs="0"/&gt;
 *         &lt;element name="matteStyle" type="{http://dete.dt.accenture.com/domain/schema/studioasset}matteStyle" minOccurs="0"/&gt;
 *         &lt;element name="horizontalResolution" type="{http://www.w3.org/2001/XMLSchema}int" minOccurs="0"/&gt;
 *         &lt;element name="verticalResolution" type="{http://www.w3.org/2001/XMLSchema}int" minOccurs="0"/&gt;
 *         &lt;element name="codecVersion" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="frameRate" type="{http://dete.dt.accenture.com/domain/schema/studioasset}frameRate" minOccurs="0"/&gt;
 *         &lt;element name="dropFrame" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/&gt;
 *         &lt;element name="scanMode" type="{http://dete.dt.accenture.com/domain/schema/studioasset}scanMode" minOccurs="0"/&gt;
 *         &lt;element name="videoProfile" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="bitRate" type="{http://www.w3.org/2001/XMLSchema}long" minOccurs="0"/&gt;
 *         &lt;element name="bitsPerSample" type="{http://www.w3.org/2001/XMLSchema}int" minOccurs="0"/&gt;
 *         &lt;element name="codec" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="keyFrameSpacing" type="{http://www.w3.org/2001/XMLSchema}int" minOccurs="0"/&gt;
 *         &lt;element name="videoChroma" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="startTimecode" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="originalHorizontalResolution" type="{http://www.w3.org/2001/XMLSchema}long" minOccurs="0"/&gt;
 *         &lt;element name="originalVerticalResolution" type="{http://www.w3.org/2001/XMLSchema}long" minOccurs="0"/&gt;
 *         &lt;element name="fieldDominance" type="{http://dete.dt.accenture.com/domain/schema/studioasset}fieldDominance" minOccurs="0"/&gt;
 *         &lt;element name="processType" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="textedType" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="localizedLanguage" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/extension&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "videoComponent", propOrder = {
    "frameAspectRatio",
    "activePictureAspectRatio",
    "cropTopLeftX",
    "cropTopLeftY",
    "cropBottomRightX",
    "cropBottomRightY",
    "runTime",
    "standard",
    "vbiLinesTop",
    "vbiLinesBottom",
    "fullFrameProcess",
    "matteStyle",
    "horizontalResolution",
    "verticalResolution",
    "codecVersion",
    "frameRate",
    "dropFrame",
    "scanMode",
    "videoProfile",
    "bitRate",
    "bitsPerSample",
    "codec",
    "keyFrameSpacing",
    "videoChroma",
    "startTimecode",
    "originalHorizontalResolution",
    "originalVerticalResolution",
    "fieldDominance",
    "processType",
    "textedType",
    "localizedLanguage"
})
public class VideoComponent
    extends Component
{

    protected String frameAspectRatio;
    protected String activePictureAspectRatio;
    protected Integer cropTopLeftX;
    protected Integer cropTopLeftY;
    protected Integer cropBottomRightX;
    protected Integer cropBottomRightY;
    protected Long runTime;
    protected String standard;
    protected Integer vbiLinesTop;
    protected Integer vbiLinesBottom;
    @XmlSchemaType(name = "string")
    protected FullFrameProcess fullFrameProcess;
    @XmlSchemaType(name = "string")
    protected MatteStyle matteStyle;
    protected Integer horizontalResolution;
    protected Integer verticalResolution;
    protected String codecVersion;
    protected String frameRate;
    protected Boolean dropFrame;
    @XmlSchemaType(name = "string")
    protected ScanMode scanMode;
    protected String videoProfile;
    protected Long bitRate;
    protected Integer bitsPerSample;
    protected String codec;
    protected Integer keyFrameSpacing;
    protected String videoChroma;
    protected String startTimecode;
    protected Long originalHorizontalResolution;
    protected Long originalVerticalResolution;
    @XmlSchemaType(name = "string")
    protected FieldDominance fieldDominance;
    protected String processType;
    protected String textedType;
    protected String localizedLanguage;

    /**
     * Gets the value of the frameAspectRatio property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFrameAspectRatio() {
        return frameAspectRatio;
    }

    /**
     * Sets the value of the frameAspectRatio property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFrameAspectRatio(String value) {
        this.frameAspectRatio = value;
    }

    /**
     * Gets the value of the activePictureAspectRatio property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getActivePictureAspectRatio() {
        return activePictureAspectRatio;
    }

    /**
     * Sets the value of the activePictureAspectRatio property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setActivePictureAspectRatio(String value) {
        this.activePictureAspectRatio = value;
    }

    /**
     * Gets the value of the cropTopLeftX property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getCropTopLeftX() {
        return cropTopLeftX;
    }

    /**
     * Sets the value of the cropTopLeftX property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setCropTopLeftX(Integer value) {
        this.cropTopLeftX = value;
    }

    /**
     * Gets the value of the cropTopLeftY property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getCropTopLeftY() {
        return cropTopLeftY;
    }

    /**
     * Sets the value of the cropTopLeftY property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setCropTopLeftY(Integer value) {
        this.cropTopLeftY = value;
    }

    /**
     * Gets the value of the cropBottomRightX property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getCropBottomRightX() {
        return cropBottomRightX;
    }

    /**
     * Sets the value of the cropBottomRightX property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setCropBottomRightX(Integer value) {
        this.cropBottomRightX = value;
    }

    /**
     * Gets the value of the cropBottomRightY property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getCropBottomRightY() {
        return cropBottomRightY;
    }

    /**
     * Sets the value of the cropBottomRightY property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setCropBottomRightY(Integer value) {
        this.cropBottomRightY = value;
    }

    /**
     * Gets the value of the runTime property.
     * 
     * @return
     *     possible object is
     *     {@link Long }
     *     
     */
    public Long getRunTime() {
        return runTime;
    }

    /**
     * Sets the value of the runTime property.
     * 
     * @param value
     *     allowed object is
     *     {@link Long }
     *     
     */
    public void setRunTime(Long value) {
        this.runTime = value;
    }

    /**
     * Gets the value of the standard property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getStandard() {
        return standard;
    }

    /**
     * Sets the value of the standard property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setStandard(String value) {
        this.standard = value;
    }

    /**
     * Gets the value of the vbiLinesTop property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getVbiLinesTop() {
        return vbiLinesTop;
    }

    /**
     * Sets the value of the vbiLinesTop property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setVbiLinesTop(Integer value) {
        this.vbiLinesTop = value;
    }

    /**
     * Gets the value of the vbiLinesBottom property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getVbiLinesBottom() {
        return vbiLinesBottom;
    }

    /**
     * Sets the value of the vbiLinesBottom property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setVbiLinesBottom(Integer value) {
        this.vbiLinesBottom = value;
    }

    /**
     * Gets the value of the fullFrameProcess property.
     * 
     * @return
     *     possible object is
     *     {@link FullFrameProcess }
     *     
     */
    public FullFrameProcess getFullFrameProcess() {
        return fullFrameProcess;
    }

    /**
     * Sets the value of the fullFrameProcess property.
     * 
     * @param value
     *     allowed object is
     *     {@link FullFrameProcess }
     *     
     */
    public void setFullFrameProcess(FullFrameProcess value) {
        this.fullFrameProcess = value;
    }

    /**
     * Gets the value of the matteStyle property.
     * 
     * @return
     *     possible object is
     *     {@link MatteStyle }
     *     
     */
    public MatteStyle getMatteStyle() {
        return matteStyle;
    }

    /**
     * Sets the value of the matteStyle property.
     * 
     * @param value
     *     allowed object is
     *     {@link MatteStyle }
     *     
     */
    public void setMatteStyle(MatteStyle value) {
        this.matteStyle = value;
    }

    /**
     * Gets the value of the horizontalResolution property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getHorizontalResolution() {
        return horizontalResolution;
    }

    /**
     * Sets the value of the horizontalResolution property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setHorizontalResolution(Integer value) {
        this.horizontalResolution = value;
    }

    /**
     * Gets the value of the verticalResolution property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getVerticalResolution() {
        return verticalResolution;
    }

    /**
     * Sets the value of the verticalResolution property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setVerticalResolution(Integer value) {
        this.verticalResolution = value;
    }

    /**
     * Gets the value of the codecVersion property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCodecVersion() {
        return codecVersion;
    }

    /**
     * Sets the value of the codecVersion property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCodecVersion(String value) {
        this.codecVersion = value;
    }

    /**
     * Gets the value of the frameRate property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFrameRate() {
        return frameRate;
    }

    /**
     * Sets the value of the frameRate property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFrameRate(String value) {
        this.frameRate = value;
    }

    /**
     * Gets the value of the dropFrame property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isDropFrame() {
        return dropFrame;
    }

    /**
     * Sets the value of the dropFrame property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setDropFrame(Boolean value) {
        this.dropFrame = value;
    }

    /**
     * Gets the value of the scanMode property.
     * 
     * @return
     *     possible object is
     *     {@link ScanMode }
     *     
     */
    public ScanMode getScanMode() {
        return scanMode;
    }

    /**
     * Sets the value of the scanMode property.
     * 
     * @param value
     *     allowed object is
     *     {@link ScanMode }
     *     
     */
    public void setScanMode(ScanMode value) {
        this.scanMode = value;
    }

    /**
     * Gets the value of the videoProfile property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getVideoProfile() {
        return videoProfile;
    }

    /**
     * Sets the value of the videoProfile property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setVideoProfile(String value) {
        this.videoProfile = value;
    }

    /**
     * Gets the value of the bitRate property.
     * 
     * @return
     *     possible object is
     *     {@link Long }
     *     
     */
    public Long getBitRate() {
        return bitRate;
    }

    /**
     * Sets the value of the bitRate property.
     * 
     * @param value
     *     allowed object is
     *     {@link Long }
     *     
     */
    public void setBitRate(Long value) {
        this.bitRate = value;
    }

    /**
     * Gets the value of the bitsPerSample property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getBitsPerSample() {
        return bitsPerSample;
    }

    /**
     * Sets the value of the bitsPerSample property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setBitsPerSample(Integer value) {
        this.bitsPerSample = value;
    }

    /**
     * Gets the value of the codec property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCodec() {
        return codec;
    }

    /**
     * Sets the value of the codec property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCodec(String value) {
        this.codec = value;
    }

    /**
     * Gets the value of the keyFrameSpacing property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getKeyFrameSpacing() {
        return keyFrameSpacing;
    }

    /**
     * Sets the value of the keyFrameSpacing property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setKeyFrameSpacing(Integer value) {
        this.keyFrameSpacing = value;
    }

    /**
     * Gets the value of the videoChroma property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getVideoChroma() {
        return videoChroma;
    }

    /**
     * Sets the value of the videoChroma property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setVideoChroma(String value) {
        this.videoChroma = value;
    }

    /**
     * Gets the value of the startTimecode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getStartTimecode() {
        return startTimecode;
    }

    /**
     * Sets the value of the startTimecode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setStartTimecode(String value) {
        this.startTimecode = value;
    }

    /**
     * Gets the value of the originalHorizontalResolution property.
     * 
     * @return
     *     possible object is
     *     {@link Long }
     *     
     */
    public Long getOriginalHorizontalResolution() {
        return originalHorizontalResolution;
    }

    /**
     * Sets the value of the originalHorizontalResolution property.
     * 
     * @param value
     *     allowed object is
     *     {@link Long }
     *     
     */
    public void setOriginalHorizontalResolution(Long value) {
        this.originalHorizontalResolution = value;
    }

    /**
     * Gets the value of the originalVerticalResolution property.
     * 
     * @return
     *     possible object is
     *     {@link Long }
     *     
     */
    public Long getOriginalVerticalResolution() {
        return originalVerticalResolution;
    }

    /**
     * Sets the value of the originalVerticalResolution property.
     * 
     * @param value
     *     allowed object is
     *     {@link Long }
     *     
     */
    public void setOriginalVerticalResolution(Long value) {
        this.originalVerticalResolution = value;
    }

    /**
     * Gets the value of the fieldDominance property.
     * 
     * @return
     *     possible object is
     *     {@link FieldDominance }
     *     
     */
    public FieldDominance getFieldDominance() {
        return fieldDominance;
    }

    /**
     * Sets the value of the fieldDominance property.
     * 
     * @param value
     *     allowed object is
     *     {@link FieldDominance }
     *     
     */
    public void setFieldDominance(FieldDominance value) {
        this.fieldDominance = value;
    }

    /**
     * Gets the value of the processType property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getProcessType() {
        return processType;
    }

    /**
     * Sets the value of the processType property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setProcessType(String value) {
        this.processType = value;
    }

    /**
     * Gets the value of the textedType property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTextedType() {
        return textedType;
    }

    /**
     * Sets the value of the textedType property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTextedType(String value) {
        this.textedType = value;
    }

    /**
     * Gets the value of the localizedLanguage property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLocalizedLanguage() {
        return localizedLanguage;
    }

    /**
     * Sets the value of the localizedLanguage property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLocalizedLanguage(String value) {
        this.localizedLanguage = value;
    }

}
