//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.07.12 at 09:24:55 PM ICT 
//


package com.accenture.dt.dete.domain.schema.digitalasset;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.bind.annotation.XmlType;
import com.accenture.dt.dete.domain.schema.common.BaseEntity;
import com.accenture.dt.dete.domain.schema.studioasset.ConformanceAssociation;
import com.accenture.dt.dete.domain.schema.studioasset.StandaloneAssociation;


/**
 * <p>Java class for assetComponentAssociation complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="assetComponentAssociation"&gt;
 *   &lt;complexContent&gt;
 *     &lt;extension base="{http://dete.dt.accenture.com/domain/schema/common}baseEntity"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="qcStatus" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="original" type="{http://www.w3.org/2001/XMLSchema}boolean"/&gt;
 *         &lt;element name="component" type="{http://dete.dt.accenture.com/domain/schema/digitalasset}component" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/extension&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "assetComponentAssociation", propOrder = {
    "qcStatus",
    "original",
    "component"
})
@XmlSeeAlso({
    ConformanceAssociation.class,
    StandaloneAssociation.class
})
public abstract class AssetComponentAssociation
    extends BaseEntity
{

    protected String qcStatus;
    protected boolean original;
    protected Component component;

    /**
     * Gets the value of the qcStatus property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getQcStatus() {
        return qcStatus;
    }

    /**
     * Sets the value of the qcStatus property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setQcStatus(String value) {
        this.qcStatus = value;
    }

    /**
     * Gets the value of the original property.
     * 
     */
    public boolean isOriginal() {
        return original;
    }

    /**
     * Sets the value of the original property.
     * 
     */
    public void setOriginal(boolean value) {
        this.original = value;
    }

    /**
     * Gets the value of the component property.
     * 
     * @return
     *     possible object is
     *     {@link Component }
     *     
     */
    public Component getComponent() {
        return component;
    }

    /**
     * Sets the value of the component property.
     * 
     * @param value
     *     allowed object is
     *     {@link Component }
     *     
     */
    public void setComponent(Component value) {
        this.component = value;
    }

}
