//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.07.12 at 09:24:55 PM ICT 
//


package com.accenture.dt.dete.domain.schema.digitalasset;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.bind.annotation.XmlType;
import com.accenture.dt.dete.domain.schema.common.BaseEntity;
import com.accenture.dt.dete.domain.schema.studioasset.AudioChannelComponent;
import com.accenture.dt.dete.domain.schema.studioasset.ClosedCaptionComponent;
import com.accenture.dt.dete.domain.schema.studioasset.SubtitleComponent;
import com.accenture.dt.dete.domain.schema.studioasset.VideoComponent;


/**
 * <p>Java class for component complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="component"&gt;
 *   &lt;complexContent&gt;
 *     &lt;extension base="{http://dete.dt.accenture.com/domain/schema/common}baseEntity"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="deteId" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="status" type="{http://dete.dt.accenture.com/domain/schema/digitalasset}componentStatus" minOccurs="0"/&gt;
 *         &lt;element name="path" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="name" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="componentType" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="qcStatus" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="componentFile" type="{http://dete.dt.accenture.com/domain/schema/digitalasset}componentFile" minOccurs="0"/&gt;
 *         &lt;element name="parentSources" type="{http://dete.dt.accenture.com/domain/schema/digitalasset}parentSource" maxOccurs="unbounded" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/extension&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "component", propOrder = {
    "deteId",
    "status",
    "path",
    "name",
    "componentType",
    "qcStatus",
    "componentFile",
    "parentSources"
})
@XmlSeeAlso({
    AudioChannelComponent.class,
    CompositeComponent.class,
    ClosedCaptionComponent.class,
    SubtitleComponent.class,
    VideoComponent.class
})
public abstract class Component
    extends BaseEntity
{

    protected String deteId;
    @XmlSchemaType(name = "string")
    protected ComponentStatus status;
    protected String path;
    protected String name;
    protected String componentType;
    protected String qcStatus;
    protected ComponentFile componentFile;
    @XmlElement(nillable = true)
    protected List<ParentSource> parentSources;

    /**
     * Gets the value of the deteId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDeteId() {
        return deteId;
    }

    /**
     * Sets the value of the deteId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDeteId(String value) {
        this.deteId = value;
    }

    /**
     * Gets the value of the status property.
     * 
     * @return
     *     possible object is
     *     {@link ComponentStatus }
     *     
     */
    public ComponentStatus getStatus() {
        return status;
    }

    /**
     * Sets the value of the status property.
     * 
     * @param value
     *     allowed object is
     *     {@link ComponentStatus }
     *     
     */
    public void setStatus(ComponentStatus value) {
        this.status = value;
    }

    /**
     * Gets the value of the path property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPath() {
        return path;
    }

    /**
     * Sets the value of the path property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPath(String value) {
        this.path = value;
    }

    /**
     * Gets the value of the name property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getName() {
        return name;
    }

    /**
     * Sets the value of the name property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setName(String value) {
        this.name = value;
    }

    /**
     * Gets the value of the componentType property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getComponentType() {
        return componentType;
    }

    /**
     * Sets the value of the componentType property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setComponentType(String value) {
        this.componentType = value;
    }

    /**
     * Gets the value of the qcStatus property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getQcStatus() {
        return qcStatus;
    }

    /**
     * Sets the value of the qcStatus property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setQcStatus(String value) {
        this.qcStatus = value;
    }

    /**
     * Gets the value of the componentFile property.
     * 
     * @return
     *     possible object is
     *     {@link ComponentFile }
     *     
     */
    public ComponentFile getComponentFile() {
        return componentFile;
    }

    /**
     * Sets the value of the componentFile property.
     * 
     * @param value
     *     allowed object is
     *     {@link ComponentFile }
     *     
     */
    public void setComponentFile(ComponentFile value) {
        this.componentFile = value;
    }

    /**
     * Gets the value of the parentSources property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the parentSources property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getParentSources().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link ParentSource }
     * 
     * 
     */
    public List<ParentSource> getParentSources() {
        if (parentSources == null) {
            parentSources = new ArrayList<ParentSource>();
        }
        return this.parentSources;
    }

}
