//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.07.12 at 09:24:55 PM ICT 
//


package com.accenture.dt.dete.domain.schema.digitalasset;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for componentStatus.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="componentStatus"&gt;
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *     &lt;enumeration value="IN"/&gt;
 *     &lt;enumeration value="TOBE_INGESTED"/&gt;
 *     &lt;enumeration value="INGESTING"/&gt;
 *     &lt;enumeration value="TOBE_FIXED"/&gt;
 *     &lt;enumeration value="LOGICALLY_DELETED"/&gt;
 *     &lt;enumeration value="PHYSICALLY_DELETED"/&gt;
 *   &lt;/restriction&gt;
 * &lt;/simpleType&gt;
 * </pre>
 * 
 */
@XmlType(name = "componentStatus")
@XmlEnum
public enum ComponentStatus {

    IN,
    TOBE_INGESTED,
    INGESTING,
    TOBE_FIXED,
    LOGICALLY_DELETED,
    PHYSICALLY_DELETED;

    public String value() {
        return name();
    }

    public static ComponentStatus fromValue(String v) {
        return valueOf(v);
    }

}
