//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.07.12 at 09:24:55 PM ICT 
//


package com.accenture.dt.dete.domain.schema.digitalasset;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for externalObjectType.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="externalObjectType"&gt;
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *     &lt;enumeration value="DETE_EMASTER"/&gt;
 *     &lt;enumeration value="GATOR_TAPE"/&gt;
 *     &lt;enumeration value="MPI_TAPE"/&gt;
 *     &lt;enumeration value="EXTERNAL_TAPE"/&gt;
 *   &lt;/restriction&gt;
 * &lt;/simpleType&gt;
 * </pre>
 * 
 */
@XmlType(name = "externalObjectType")
@XmlEnum
public enum ExternalObjectType {

    DETE_EMASTER,
    GATOR_TAPE,
    MPI_TAPE,
    EXTERNAL_TAPE;

    public String value() {
        return name();
    }

    public static ExternalObjectType fromValue(String v) {
        return valueOf(v);
    }

}
