//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.07.12 at 09:24:55 PM ICT 
//


package com.accenture.dt.dete.domain.schema.digitalasset;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.accenture.dt.dete.domain.schema.digitalasset package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _Asset_QNAME = new QName("http://dete.dt.accenture.com/domain/schema/digitalasset", "asset");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.accenture.dt.dete.domain.schema.digitalasset
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link ComponentFile }
     * 
     */
    public ComponentFile createComponentFile() {
        return new ComponentFile();
    }

    /**
     * Create an instance of {@link ParentSource }
     * 
     */
    public ParentSource createParentSource() {
        return new ParentSource();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Asset }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://dete.dt.accenture.com/domain/schema/digitalasset", name = "asset")
    public JAXBElement<Asset> createAsset(Asset value) {
        return new JAXBElement<Asset>(_Asset_QNAME, Asset.class, null, value);
    }

}
