//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.07.12 at 09:24:55 PM ICT 
//


package com.accenture.dt.dete.domain.schema.digitalasset;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import com.accenture.dt.dete.domain.schema.common.BaseEntity;


/**
 * <p>Java class for parentSource complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="parentSource"&gt;
 *   &lt;complexContent&gt;
 *     &lt;extension base="{http://dete.dt.accenture.com/domain/schema/common}baseEntity"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="deteId" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="externalId" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="externalObjectType" type="{http://dete.dt.accenture.com/domain/schema/digitalasset}externalObjectType" minOccurs="0"/&gt;
 *         &lt;element name="externalSystem" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="fromElementSet" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/extension&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "parentSource", propOrder = {
    "deteId",
    "externalId",
    "externalObjectType",
    "externalSystem",
    "fromElementSet"
})
public class ParentSource
    extends BaseEntity
{

    protected String deteId;
    protected String externalId;
    @XmlSchemaType(name = "string")
    protected ExternalObjectType externalObjectType;
    protected String externalSystem;
    protected Boolean fromElementSet;

    /**
     * Gets the value of the deteId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDeteId() {
        return deteId;
    }

    /**
     * Sets the value of the deteId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDeteId(String value) {
        this.deteId = value;
    }

    /**
     * Gets the value of the externalId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getExternalId() {
        return externalId;
    }

    /**
     * Sets the value of the externalId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setExternalId(String value) {
        this.externalId = value;
    }

    /**
     * Gets the value of the externalObjectType property.
     * 
     * @return
     *     possible object is
     *     {@link ExternalObjectType }
     *     
     */
    public ExternalObjectType getExternalObjectType() {
        return externalObjectType;
    }

    /**
     * Sets the value of the externalObjectType property.
     * 
     * @param value
     *     allowed object is
     *     {@link ExternalObjectType }
     *     
     */
    public void setExternalObjectType(ExternalObjectType value) {
        this.externalObjectType = value;
    }

    /**
     * Gets the value of the externalSystem property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getExternalSystem() {
        return externalSystem;
    }

    /**
     * Sets the value of the externalSystem property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setExternalSystem(String value) {
        this.externalSystem = value;
    }

    /**
     * Gets the value of the fromElementSet property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isFromElementSet() {
        return fromElementSet;
    }

    /**
     * Sets the value of the fromElementSet property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setFromElementSet(Boolean value) {
        this.fromElementSet = value;
    }

}
