//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.07.12 at 09:24:55 PM ICT 
//


package com.accenture.dt.dete.ws.vump.schemas;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;
import com.accenture.dt.dete.domain.schema.digitalasset.Asset;
import com.accenture.dt.dete.domain.schema.studioasset.EditedVersion;


/**
 * <p>Java class for assetFeedRequest complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="assetFeedRequest"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="asset" type="{http://dete.dt.accenture.com/domain/schema/digitalasset}asset"/&gt;
 *         &lt;element name="editedVersion" type="{http://dete.dt.accenture.com/domain/schema/studioasset}editedVersion"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "assetFeedRequest", propOrder = {
    "asset",
    "editedVersion"
})
public class AssetFeedRequest {

    @XmlElement(required = true)
    protected Asset asset;
    @XmlElement(required = true)
    protected EditedVersion editedVersion;

    /**
     * Gets the value of the asset property.
     * 
     * @return
     *     possible object is
     *     {@link Asset }
     *     
     */
    public Asset getAsset() {
        return asset;
    }

    /**
     * Sets the value of the asset property.
     * 
     * @param value
     *     allowed object is
     *     {@link Asset }
     *     
     */
    public void setAsset(Asset value) {
        this.asset = value;
    }

    /**
     * Gets the value of the editedVersion property.
     * 
     * @return
     *     possible object is
     *     {@link EditedVersion }
     *     
     */
    public EditedVersion getEditedVersion() {
        return editedVersion;
    }

    /**
     * Sets the value of the editedVersion property.
     * 
     * @param value
     *     allowed object is
     *     {@link EditedVersion }
     *     
     */
    public void setEditedVersion(EditedVersion value) {
        this.editedVersion = value;
    }

}
