//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.07.12 at 09:24:55 PM ICT 
//


package com.accenture.dt.dete.ws.vump.schemas;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.accenture.dt.dete.ws.vump.schemas package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _AssetFeedRequest_QNAME = new QName("http://dete.dt.accenture.com/ws/vump/schemas", "assetFeedRequest");
    private final static QName _AssetFeedResponse_QNAME = new QName("http://dete.dt.accenture.com/ws/vump/schemas", "assetFeedResponse");
    private final static QName _TitleFeedRequest_QNAME = new QName("http://dete.dt.accenture.com/ws/vump/schemas", "titleFeedRequest");
    private final static QName _TitleFeedResponse_QNAME = new QName("http://dete.dt.accenture.com/ws/vump/schemas", "titleFeedResponse");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.accenture.dt.dete.ws.vump.schemas
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link AssetFeedRequest }
     * 
     */
    public AssetFeedRequest createAssetFeedRequest() {
        return new AssetFeedRequest();
    }

    /**
     * Create an instance of {@link AssetFeedResponse }
     * 
     */
    public AssetFeedResponse createAssetFeedResponse() {
        return new AssetFeedResponse();
    }

    /**
     * Create an instance of {@link TitleFeedRequest }
     * 
     */
    public TitleFeedRequest createTitleFeedRequest() {
        return new TitleFeedRequest();
    }

    /**
     * Create an instance of {@link TitleFeedResponse }
     * 
     */
    public TitleFeedResponse createTitleFeedResponse() {
        return new TitleFeedResponse();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link AssetFeedRequest }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://dete.dt.accenture.com/ws/vump/schemas", name = "assetFeedRequest")
    public JAXBElement<AssetFeedRequest> createAssetFeedRequest(AssetFeedRequest value) {
        return new JAXBElement<AssetFeedRequest>(_AssetFeedRequest_QNAME, AssetFeedRequest.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link AssetFeedResponse }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://dete.dt.accenture.com/ws/vump/schemas", name = "assetFeedResponse")
    public JAXBElement<AssetFeedResponse> createAssetFeedResponse(AssetFeedResponse value) {
        return new JAXBElement<AssetFeedResponse>(_AssetFeedResponse_QNAME, AssetFeedResponse.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link TitleFeedRequest }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://dete.dt.accenture.com/ws/vump/schemas", name = "titleFeedRequest")
    public JAXBElement<TitleFeedRequest> createTitleFeedRequest(TitleFeedRequest value) {
        return new JAXBElement<TitleFeedRequest>(_TitleFeedRequest_QNAME, TitleFeedRequest.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link TitleFeedResponse }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://dete.dt.accenture.com/ws/vump/schemas", name = "titleFeedResponse")
    public JAXBElement<TitleFeedResponse> createTitleFeedResponse(TitleFeedResponse value) {
        return new JAXBElement<TitleFeedResponse>(_TitleFeedResponse_QNAME, TitleFeedResponse.class, null, value);
    }

}
